In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv('glass.csv')

In [3]:
display(df)

          RI     Na    Mg    Al     Si     K    Ca    Ba   Fe  Type
0    1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.00  0.0     1
1    1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.00  0.0     1
2    1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.00  0.0     1
3    1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.00  0.0     1
4    1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.00  0.0     1
..       ...    ...   ...   ...    ...   ...   ...   ...  ...   ...
209  1.51623  14.14  0.00  2.88  72.61  0.08  9.18  1.06  0.0     7
210  1.51685  14.92  0.00  1.99  73.06  0.00  8.40  1.59  0.0     7
211  1.52065  14.36  0.00  2.02  73.42  0.00  8.44  1.64  0.0     7
212  1.51651  14.38  0.00  1.94  73.61  0.00  8.48  1.57  0.0     7
213  1.51711  14.23  0.00  2.08  73.36  0.00  8.62  1.67  0.0     7

[214 rows x 10 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 214 entries, 0 to 213
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   RI      214 non-null    float64
 1   Na      214 non-null    float64
 2   Mg      214 non-null    float64
 3   Al      214 non-null    float64
 4   Si      214 non-null    float64
 5   K       214 non-null    float64
 6   Ca      214 non-null    float64
 7   Ba      214 non-null    float64
 8   Fe      214 non-null    float64
 9   Type    214 non-null    int64
dtypes: float64(9), int64(1)
memory usage: 16.8 KB

In [5]:
df.columns

Index(['RI', 'Na', 'Mg', 'Al', 'Si', 'K', 'Ca', 'Ba', 'Fe', 'Type'], dtype='object')

In [6]:
df.shape

(214, 10)

In [8]:
cor=df.corr()
cor.style.background_gradient(cmap='Purples')

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
x=df.iloc[:,0:10]
y=df['Type']

In [11]:
xtr,xts,ytr,yts=train_test_split(x,y,test_size=0.2,random_state=0)

In [12]:
xtr

          RI     Na    Mg    Al     Si     K    Ca   Ba    Fe  Type
16   1.51784  12.68  3.67  1.16  73.11  0.61  8.70  0.0  0.00     1
135  1.51789  13.19  3.90  1.30  72.33  0.55  8.44  0.0  0.28     2
122  1.51687  13.23  3.54  1.48  72.84  0.56  8.10  0.0  0.00     2
22   1.51736  12.78  3.62  1.29  72.79  0.59  8.70  0.0  0.00     1
80   1.51592  12.86  3.52  2.12  72.66  0.69  7.97  0.0  0.00     2
..       ...    ...   ...   ...    ...   ...   ...  ...   ...   ...
67   1.52152  13.05  3.65  0.87  72.32  0.19  9.85  0.0  0.17     1
192  1.51623  14.20  0.00  2.79  73.46  0.04  9.04  0.4  0.09     7
117  1.51708  13.72  3.68  1.81  72.06  0.64  7.88  0.0  0.00     2
47   1.52667  13.99  3.70  0.71  71.57  0.02  9.82  0.0  0.10     1
172  1.51321  13.00  0.00  3.02  70.70  6.21  6.93  0.0  0.00     5

[171 rows x 10 columns]

In [13]:
from sklearn.ensemble import RandomForestClassifier

In [14]:
mod=RandomForestClassifier()

In [15]:
mod.fit(xtr,ytr)

RandomForestClassifier()

In [16]:
pred=mod.predict(xts)
print(pred)

[7 1 2 6 5 2 2 2 1 2 1 2 3 2 2 7 2 1 3 3 5 2 7 7 2 1 7 1 2 2 1 1 2 2 2 3 1
 3 2 7 2 6 2]

In [17]:
# Accuracy Checking.
from sklearn.metrics import accuracy_score

In [18]:
acc=accuracy_score(yts,pred)
print("Accuracy is:",acc*100)

Accuracy is: 100.0

In [19]:
# Evalution Metrics
from sklearn.metrics import confusion_matrix

In [20]:
# Confuse Matrix
c=confusion_matrix(yts,pred)
print("Confusion Matrix is: \n",c)

Confusion Matrix is:
 [[ 9  0  0  0  0  0]
 [ 0 19  0  0  0  0]
 [ 0  0  5  0  0  0]
 [ 0  0  0  2  0  0]
 [ 0  0  0  0  2  0]
 [ 0  0  0  0  0  6]]